name: provider_template #TODO Change app name here
description: A template with the folder structure for using Provider with flutter.


publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  change_app_package_name: ^1.0.0


flutter:
  uses-material-design: true
